---
abstract: 'Command Line Interface I/O via any of Telnet, SSH or Serial port'
author:
  - 'Ludovico Stevens <lstevens@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Control-CLI
provides:
  Control::CLI:
    file: lib/Control/CLI.pm
    version: 1.00
requires:
  Term::ReadKey: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
